# FROM ubuntu:22.04
FROM mcr.microsoft.com/devcontainers/base:bullseye
#ENV HOME="/root"
#ENV NVM_DIR="${HOME}/.nvm"
#ENV NVM_VERSION=v0.39.7
#ENV NODE_VERSION=20.10.0
#ENV PMPM_VERSION=8.12.1


#RUN apt-get update \
#    && apt-get install -y --no-install-recommends build-essential\
#        libssl-dev \
#        git \
#        curl \
#        ca-certificates
#    && git clone https://github.com/nvm-sh/nvm.git "${NVM_DIR}" 

#WORKDIR  "${NVM_DIR}"

#RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

#RUN git checkout ${NVM_VERSION} \
#    && \. "./nvm.sh" \
#    && nvm install "${NODE_VERSION}" \
#    && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> "${HOME}/.bashrc" \
#    && echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> "${HOME}/.bashrc" 

#RUN npm install -g pnpm  

#WORKDIR "${HOME}"